/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdbool.h>
#include <stdint.h>
#include <string.h>

#include "main.h"
#include "USART.h"
#include "GPIO.h"
#include "I2C.h"
#include "DHT11.h"
#include "delay.h"
#include "SH1106.h"
#include "BH1750.h"
#include "ADC.h"
#include "relay.h"
#include "control.h"

/* Private variables */
uint32_t APB1CLK_SPEED;
uint32_t APB2CLK_SPEED;
extern uint32_t SystemCoreClock;
DHT11_TypeDef dht11;
float lux_f = 0;
uint16_t soilMoisture = 0;
UART_Handle_t ESP32_UART = {ESP32_PORT,
							FULL_DUPLEX,
							115200,
							false,
							false,
							false,
							0,0,0};
/* Private function prototypes */
int32_t SystemAPB1_Clock_Speed(void);
int32_t SystemAPB2_Clock_Speed(void);
void MCU_Clock_Setup(void);
static void OLED_ShowLines(const char *line1, const char *line2, const char *line3);



#if ((MCU_HSE_HZ / MCU_PLL_M_VALUE) < 1000000ULL) || ((MCU_HSE_HZ / MCU_PLL_M_VALUE) > 2000000ULL)
#error "HSE frequency divided by PLL_M must stay within the STM32F411 PLL input range"
#endif

#if (((MCU_TARGET_SYSCLK_HZ * MCU_PLL_M_VALUE * MCU_PLL_P_VALUE) % MCU_HSE_HZ) != 0ULL)
#error "HSE_VALUE is incompatible with the current PLL settings"
#endif

#define MCU_PLL_N_VALUE  ((MCU_TARGET_SYSCLK_HZ * MCU_PLL_M_VALUE * MCU_PLL_P_VALUE) / MCU_HSE_HZ)

#if ((MCU_PLL_N_VALUE < 192U) || (MCU_PLL_N_VALUE > 432U))
#error "Computed PLL_N is outside the STM32F411 valid range"
#endif

int main(void)
{
	/* Variable declarations */
	char line[3][MAX_OLED_CHARS + 1];
	char buf[32];

	/* Initialize the system clock */
	SystemInit();
	MCU_Clock_Setup();
	DWT_Init();

	SH1106_Init(OLED_PORT);
	BH1750_Init(BH1750_PORT);
	DHT11_Init(DHT11_PORT, DHT11_PIN);
	ADC_Init();
	UART_Init(&ESP32_UART);
	Relay_Init(GPIOB, GPIO_PIN_0);
	Relay_Init(GPIOB, GPIO_PIN_1);
	Control_Init();
	// Configure PC13 as output for on-board LED
	GPIO_Pin_Setup(GPIOC, GPIO_PIN_13, GENERAL_PURPOSE_OUTPUT_PUSHPULL, NONE);

	OLED_ShowLines("DHT11 OLED SH1106", "Initializing...", "");
	DWT_delay_ms(500);

	/* Loop forever */
	while (1)
	{
		GPIOC->ODR ^= GPIO_ODR_OD13; // Blink on-board LED

		if (DHT11_read(&dht11))
			 snprintf(line[0], sizeof(line[0]), "T: %u C  H: %u%%", dht11.temperature,dht11.humidity);
		else snprintf(line[0], sizeof(line[0]), "DHT11 Error");

		soilMoisture = ADC_Read();
		lux_f = BH1750_ReadLux(BH1750_CONT_H_RES_MODE);

		if (lux_f >= 0)
			snprintf(line[1], sizeof(line[1]), "L:%u lx S: %u", (uint16_t)lux_f, soilMoisture);
		else snprintf(line[1], sizeof(line[1]), "Lux Error");

		snprintf(buf, sizeof(buf), "T:%u,H:%u,L:%u,S:%u\n", dht11.temperature, dht11.humidity, (uint16_t)lux_f,soilMoisture);
		UART_Transmit_Buffer(&ESP32_UART, buf);
		memset(buf,'\0',sizeof(buf));

		OLED_ShowLines(line[0], line[1], line[2]);
		Control_Process();

		DWT_delay_ms(1000);
	}
}

/* -----------------------Function Prototype----------------------------*/
//---------------------------------------------------------------------//
int32_t SystemAPB1_Clock_Speed(void)
{
	return (SystemCoreClock >> APBPrescTable[(RCC->CFGR & RCC_CFGR_PPRE1) >> RCC_CFGR_PPRE1_Pos]);
}

int32_t SystemAPB2_Clock_Speed(void)
{
	return (SystemCoreClock >> APBPrescTable[(RCC->CFGR & RCC_CFGR_PPRE2) >> RCC_CFGR_PPRE2_Pos]);
}

void MCU_Clock_Setup(void)
{
	SystemInit();
	// Clock is derived from HSE_VALUE, so PLL_N adapts to the external crystal.
	uint8_t pll_m = (uint8_t)MCU_PLL_M_VALUE;
	uint8_t pll_n = (uint8_t)MCU_PLL_N_VALUE;
	uint8_t pll_p = 0; // 0x00: PLLP = 2, 0x01: PLLP = 4, 0x02: PLLP = 6, 0x03: PLLP = 8
	uint8_t pll_q = 4; // Used for USB, SDIO, RNG (48MHz), Using ClockCoreSystem 96MHz

	RCC->PLLCFGR = 0x00000000;

	RCC->CR |= RCC_CR_HSEON;
	while (!(RCC->CR & RCC_CR_HSERDY)) {}
	RCC->APB1ENR |= RCC_APB1ENR_PWREN;
	PWR->CR |= PWR_CR_VOS;
	FLASH->ACR |= FLASH_ACR_ICEN | FLASH_ACR_PRFTEN | FLASH_ACR_DCEN | FLASH_ACR_LATENCY_3WS;
	RCC->PLLCFGR |= (pll_q << 24) | (pll_p << 16) | (pll_n << 6) | (pll_m << 0);
	RCC->PLLCFGR |= 1 << 22;
	//  RCC->PLLCFGR = 0x4403019;
	RCC->CFGR |= RCC_CFGR_HPRE_DIV1;
	RCC->CFGR |= RCC_CFGR_PPRE1_DIV2;
	RCC->CFGR |= RCC_CFGR_PPRE2_DIV1;
	//	RCC-> APB2ENR |= 0x4000;
	RCC->CR |= RCC_CR_PLLON;
	while (!(RCC->CR & RCC_CR_PLLRDY)) {}
	//	RCC -> CR |= RCC_CR_PLLI2SON;
	//	while(!(RCC->CR & RCC_CR_PLLI2SRDY)){}
	RCC->CFGR |= RCC_CFGR_SW_PLL;
	while ((RCC->CFGR & RCC_CFGR_SWS_PLL) != RCC_CFGR_SWS_PLL)
		;
	SystemCoreClockUpdate();
	// SysTick_Config(SystemCoreClock/1000);
	APB1CLK_SPEED = SystemAPB1_Clock_Speed();
	APB2CLK_SPEED = SystemAPB2_Clock_Speed();
	RCC->APB2ENR |= RCC_APB2ENR_SYSCFGEN;
}

static void OLED_ShowLines(const char *line1, const char *line2, const char *line3)
{
	char display_line1[MAX_OLED_CHARS + 1];
	char display_line2[MAX_OLED_CHARS + 1];
	char display_line3[MAX_OLED_CHARS + 1];

	snprintf(display_line1, sizeof(display_line1), "%s", line1);
	snprintf(display_line2, sizeof(display_line2), "%s", line2);
	snprintf(display_line3, sizeof(display_line3), "%s", line3);

	SH1106_Fill(SH1106_COLOR_BLACK);
	SH1106_GotoXY(0, 0);
	SH1106_Puts(display_line1, &Font_7x10, SH1106_COLOR_WHITE);
	SH1106_GotoXY(0, 16);
	SH1106_Puts(display_line2, &Font_7x10, SH1106_COLOR_WHITE);
	SH1106_GotoXY(0, 32);
	SH1106_Puts(display_line3, &Font_7x10, SH1106_COLOR_WHITE);
	SH1106_UpdateScreen();
}
